---
- name: configure first control plane node
  hosts: control-plane[0]

  roles:
    - role: k3s
      vars:
        cluster_init: true

  post_tasks:
    - name: wait for first node to become ready
      ansible.builtin.shell: kubectl wait --for=condition=Ready nodes --selector 'kubernetes.io/hostname={{ht_name}}' --timeout=600s
      environment:
        KUBECONFIG: "{{playbook_dir | basename}}/sharedfiles/manifests/.kubeconfig.yaml"
      async: 600
      poll: 5
      delegate_to: 127.0.0.1

- name: configure rest of the control plane nodes
  hosts: control-plane[1:]

  roles:
    - role: k3s

  post_tasks:
    - name: wait for rest of the control plane nodes to become ready
      ansible.builtin.shell: kubectl wait --for=condition=Ready nodes --selector 'kubernetes.io/hostname={{ht_name}}' --timeout=600s
      environment:
        KUBECONFIG: "{{playbook_dir | basename}}/sharedfiles/manifests/.kubeconfig.yaml"
      async: 600
      poll: 5
      delegate_to: 127.0.0.1

- name: configure worker nodes
  hosts: worker

  roles:
    - role: k3s

  post_tasks:
    - name: wait for worker nodes to become ready
      ansible.builtin.shell: kubectl wait --for=condition=Ready nodes --selector 'kubernetes.io/hostname={{ht_name}}' --timeout=600s
      environment:
        KUBECONFIG: "{{playbook_dir | basename}}/sharedfiles/manifests/.kubeconfig.yaml"
      async: 600
      poll: 5
      delegate_to: 127.0.0.1
